server:
  port: ${PORT:8000}

bootstrap:
  servers: ${KAFKA_HOST:localhost:9092}

spring:
  application:
    name: account-ms
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/account-ms?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
