
server:
  port: ${PORT:8040}

bootstrap:
  servers: ${KAFKA_HOST:localhost:9092}

spring:
  application:
    name: transfer-ms
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/transfer-ms?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
